import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Navigation from '@/components/navigation';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-black text-zinc-500 lowercase">
        <Navigation/>
        <div className="min-h-screen min-w-screen flex items-center justify-center">
          <main className="min-w-full min-h-full max-w-md flex flex-col items-center justify-center">{children}</main>
        </div>
      </body>
    </html>
  );
}
